version: '2.2'

networks:
  default:

services:

  php-min:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      target: min
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
        - PECL_XDEBUG_INSTALL_SUFFIX
        - PECL_MONGODB_INSTALL_SUFFIX
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}-min
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
      - PHP_IDE_CONFIG=serverName=Docker
    volumes:
      - ./tests:/tests:delegated
      # Framework testing
      - ./_host-volumes/yii2:/yii2:delegated
      # Application testing
      - ./_host-volumes/app:/app:delegated
      # Composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    networks:
      default:
        aliases:
          - php

  php-dev:
    extends:
      service: php-min
    build:
      target: dev
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}

  mysql:
    container_name: mysql
    image: mysql:8.0.21
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "${MYSQL_FORWARD_PORT:-33067}:3306"
    environment:
      - MYSQL_DATABASE=books_db
      - MYSQL_USER=book_user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
